version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    ports:
      - "1221:1221"
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env-non-dev


  app:
    build:
      context: .
    container_name: delivery_app
    env_file:
      - .env-non-dev
    command: ["/delivery_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ["/delivery_app/docker/celery.sh", "celery"]
    depends_on:
      - redis


  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: ["/delivery_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
      - redis
    ports:
      - "5050:5050"
    env_file:
      - .env-non-dev
