"""change name field to photo_1&photo_2 to dish table

Revision ID: 9f6e4a849dd0
Revises: ca665b5340f6
Create Date: 2023-12-18 03:12:47.706711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6e4a849dd0'
down_revision = 'ca665b5340f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('photo_1', sa.String(), nullable=True))
    op.add_column('dish', sa.Column('photo_2', sa.String(), nullable=True))
    op.drop_column('dish', 'photo1')
    op.drop_column('dish', 'photo2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('photo2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dish', sa.Column('photo1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dish', 'photo_2')
    op.drop_column('dish', 'photo_1')
    # ### end Alembic commands ###
