"""empty message

Revision ID: ca665b5340f6
Revises: 6c25728020a7
Create Date: 2023-07-06 15:50:31.886629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca665b5340f6'
down_revision = '6c25728020a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
