"""full tables

Revision ID: e70de0b275dd
Revises: 74fe53655f15
Create Date: 2023-06-23 19:24:13.361055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70de0b275dd'
down_revision = '74fe53655f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
